version: '3'
services:
  app:
    container_name: qr-app
    image: qr-app:1.0.0
    build: .
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8051:8051"
    volumes:
      - ~/docker/redis:/redis-service/logs
  redis:
    container_name: redis
    image: redis:7.0.9-alpine
    hostname: redis
    ports:
      - "6379:6379"